name: physix
channels:
  - defaults
  - nvidia/label/cuda-12.4.0
  - conda-forge
dependencies:
  - python=3.10
  - cudatoolkit=11.8
  - cudnn=8.9.2.26
  - ffmpeg
  - numpy
  - hdf5
  - fonttools
  - freetype
  - pillow
  - pip
  - pip:
      - opencv-python
