# Project-wide directory path configuration
raw_data_path: '/home/tippolit/src/PhysiX/data/raw_data/physgen/data'
cleaned_data_path: '/home/tippolit/src/PhysiX/data/cleaned_data/physgen'
normalized_data_path: '/home/tippolit/src/PhysiX/data/normalized/physgen'
checkpoint_dir: '/home/tippolit/src/PhysiX/checkpoints'
embeddings_dir: '/home/tippolit/src/PhysiX/embeddings'
results_dir: '/home/tippolit/src/PhysiX/results'
tokenizer_path: '/home/tippolit/src/PhysiX/tokenizer'
cache_dir: '/home/tippolit/src/PhysiX/cache' 